import { ImageResponse } from "next/og";
import { IconArtwork } from "@/lib/icon-mark";

// One of two independent routes for this app's unmasked `purpose: "any"`
// icon (see app/icon-512/route.tsx for the other, and
// app/icon-maskable/route.tsx for the maskable purpose). These used to be
// two ids ("192", "512") of a single app/icon.tsx generateImageMetadata
// array; they're two separate Route Handlers instead because that array
// itself was the bug -- concurrent requests for two ids generated by the
// SAME generateImageMetadata route intermittently came back with a PNG of
// the correct declared byte length but corrupted, undecodable content
// under Next.js 16.3.0/Turbopack (root-caused directly against a real
// production build: reproduced with just these two ids alone, not only the
// three-id array this app had before). A plain custom Route Handler is a
// structurally different, independent code path -- its own compiled
// module, nothing shared with any sibling -- which is what actually avoids
// the bug. app/apple-icon.tsx already proved this shape works correctly.
//
// No metadata `icons` file convention is in play here on purpose -- see
// app/layout.tsx's `metadata.icons` for the explicit <link rel="icon">
// entries that replace what app/icon.tsx's generateImageMetadata used to
// auto-inject.
export const size = { width: 192, height: 192 };

export async function GET() {
  return new ImageResponse(<IconArtwork size={size.width} variant="any" />, { ...size });
}
