// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Only used by `prisma migrate dev` to create/drop its throwaway shadow
    // database for diffing. The app's runtime role (DATABASE_URL) is
    // intentionally NOCREATEDB, so this points at a role that can.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
