import { ImageResponse } from "next/og";
import { IconArtwork, type IconVariant } from "@/lib/icon-mark";

// The app's generated icon routes. The artwork itself lives in
// lib/icon-mark.tsx, shared with app/apple-icon.tsx -- see that module's
// header for why the mark is drawn from divs instead of a text glyph.
//
// Two entries via generateImageMetadata rather than one icon.tsx default
// size. 192 and 512 are what app/manifest.ts's `icons` array needs for
// Android's install prompt, and generating two genuinely distinct images
// (rather than one image referenced twice under two different declared
// `sizes`) keeps the manifest's claims about the assets actually true.
//
// The maskable purpose used to be a third id here ("512-maskable"), and
// deliberately isn't anymore -- see app/icon-maskable/route.tsx's header
// for the real, CI-reproduced bug that moved it out: concurrent requests
// for two ids generated by the SAME generateImageMetadata array
// intermittently came back corrupted under Next.js 16.3.0/Turbopack, and
// splitting the maskable variant into its own independent route is what
// actually avoids that, not merely relocates it. Keep this file to exactly
// the ids app/manifest.ts's unmasked `purpose: "any"` entries need; give any
// future additional purpose its own route the same way, don't add a third
// id here.
const ICONS = {
  "192": { size: 192, variant: "any" },
  "512": { size: 512, variant: "any" },
} as const satisfies Record<string, { size: number; variant: IconVariant }>;

export function generateImageMetadata() {
  return Object.entries(ICONS).map(([id, { size }]) => ({
    id,
    size: { width: size, height: size },
    contentType: "image/png",
  }));
}

export default async function Icon({ id }: { id: Promise<string | number> }) {
  const iconId = String(await id) as keyof typeof ICONS;
  // Falls back to the smallest icon for an id Next never generated, same as
  // the previous implementation's ternary did: a hand-typed or stale /icon
  // URL should not be a 500.
  const { size, variant } = ICONS[iconId] ?? ICONS["192"];
  return new ImageResponse(<IconArtwork size={size} variant={variant} />, {
    width: size,
    height: size,
  });
}
